name: Create a release pull-request
on:
  workflow_dispatch
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: staging
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: a,b,c
          assign: true